mysites/api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.http import HttpResponse
from blog.feeds import LatestPostsFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('feed/rss/', LatestPostsFeed(), name="rss_feed"),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

def test_view(request):
    return HttpResponse("App funcionando!")

urlpatterns += [
    path('test/', test_view),
]

mysites/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.PostList.as_view(), name='post_list'),
    path('posts_by_category/<int:category_id>/', views.category, name='posts_by_category'),
    path('tracking/', views.tracking_simple, name='tracking_simple'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),  # <-- al final
]

mysites/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Categories"    
    

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = RichTextUploadingField() # CKEditor Rich Text Field
    category = models.ManyToManyField(Category, related_name="categories")
    created_on = models.DateTimeField(auto_now_add=False, editable=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
class LinkedInAuthToken(models.Model):
    """
    Modelo para almacenar el token de acceso de LinkedIn.
    """
    access_token = models.CharField(max_length=512, unique=True, help_text="Token de acceso para la API de LinkedIn.")
    expires_in = models.IntegerField(help_text="Tiempo de vida del token en segundos.")
    created_at = models.DateTimeField(auto_now_add=True)
    profile_urn = models.CharField(max_length=128, help_text="URN del perfil de LinkedIn para publicar.")

    def __str__(self):
        return self.profile_urn
    

mysites/blog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required, user_passes_test

from .models import Post
from tracking.models import Visitor
from geoip2.database import Reader

GEOIP_DB_PATH = "api/geo/GeoLite2-City.mmdb"


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


def category(request, category_id):
    posts_by_category = Post.objects.filter(category__id=category_id)
    return render(request, "blog/posts_by_category.html", {
        "posts_by_category": posts_by_category,
    })


def is_superuser(user):
    return user.is_superuser


@login_required
@user_passes_test(is_superuser)
def tracking_simple(request):
    visitas = Visitor.objects.all().order_by('-start_time')[:20]
    total_visitas = Visitor.objects.count()

    geo_info = []
    with Reader(GEOIP_DB_PATH) as reader:
        for v in visitas:
            ip = v.ip_address
            city = country = "Desconocido"
            try:
                response = reader.city(ip)
                city = response.city.name or "Desconocido"
                country = response.country.name or "Desconocido"
            except Exception:
                pass
            geo_info.append({
                "ip": ip,
                "user_agent": v.user_agent,
                "start_time": v.start_time,
                "city": city,
                "country": country
            })

    return render(request, 'blog/tracking_simple.html', {
        'total_visitas': total_visitas,
        'visitas': geo_info
    })

mysites/blog/templates/blog/index.html
{% extends "blog/layout.html" %}


{% block heading %}
                    <h3 class=" site-heading my-4 mt-3 text-white"> My backend dev diary 📔✨ </h3>
                    <p class="text-light"> Notes on my journey learning to code & all things backend
                    </p>
{% endblock heading %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-9 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text text-muted h6">{{ post.author }} | Published on: {{ post.created_on}} </p>
                    <div class="p-3 card-text">{{ post.content|truncatechars_html:200|safe }}</div>
                    <div class="d-flex">
                        <small><p class="text-muted h7"> Categories: </p></small>&nbsp; 
                    {% for category in post.category.all %}
                    <small><p> <a href="{% url 'posts_by_category' category.id %}">{{  category.name  }} </a>   &nbsp; </p></small>
                    {% endfor %}
                    </div>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read more &rarr;</a>
                </div>
            </div>
            {% endfor %}

        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock content%}

mysites/blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <title>Alejandra Martín's Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'blog/styles.css' %}">
        <link rel="icon" href="{% static 'blog/favicon.ico' %}">

    </head>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'post_list' %}">Alejandra Martín's Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-muted">
                            <a class="nav-link active text-muted font-weight-bold" href="{% url 'post_list' %}">All categories</a>
                        </li>
                        {% for category in category_list %}
                        <li class="nav-item text-muted">
                            <a class="nav-link text-muted font-weight-bold" href="{% url 'posts_by_category' category.0 %}">  {{ category.1 }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Heading -->
        <header class="masthead">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class=" col-md-8 col-md-10 mx-auto">
                        <div class="site-heading">
                            {% block heading %}
                            <!-- Heading Goes here -->
                            {% endblock heading %}
                        </div>
                    </div>
                </div>
            </div>
        </header>

        
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">This site was made with <a href="https://www.djangoproject.com/">Django.&#128156;</p>
        </footer>
    </body>

</html>

mysites/blog/templates/blog/post_detail.html
{% extends 'blog/layout.html' %} 

{% block heading %}
                    <h3 class=" site-heading my-4 mt-3 text-white"> My backend dev diary 📔✨ </h3>
                    <p class="text-light"> Notes on my journey learning to code & all things backend
                    </p>
{% endblock heading %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-9 mt-3 left">
      <div class="card mb-4">
        <div class="card-body">
          <h3> {{ object.title }} </h3>
          <p class=" text-muted">{{ post.author }} | Published on: {{ post.created_on }}</p>
          <div class="p-3 card-text">{{ object.content | safe }}</div>
          <div class="d-flex">
            <small><p class="text-muted h7"> Categories: </p></small>&nbsp; 
            {% for category in post.category.all %}
            <small><p> <a href="{% url 'posts_by_category' category.id %}">{{  category.name  }} </a>   &nbsp; </p></small>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

mysites/blog/templates/blog/posts_by_category.html
{% extends "blog/layout.html" %}
{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> My backend dev diary 📔✨ </h3>
                    <p class="text-light">  Notes on my journey learning to code & all things backend
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts_by_category %}
            <div class="card mb-4">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <div class="card-text">{{ post.content|truncatechars_html:200|safe }}</div>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read more &rarr;</a>
                </div>
            </div>
            {% empty %}
            <p> No posts in this category. </p>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

mysites/blog/templates/blog/sidebar.html
{% block sidebar %}
{% load static %}

<!-- Sidebar Widgets Column -->
<div class="col-md-3">
<div class="card my-3">
        <h5 class="card-header">About me</h5>
    <div class="card-body" id="sidebar">
        <div class="d-flex justify-content-center"><img id="profile-picture" src="{% static 'blog/my_profile_image.png' %} " alt="profile image" class="img-thumbnail rounded" /></div>
        <div class="p-3">
            <p class="card-text">My name is Alejandra and I'm learning to code to become a backend developer. I also love videogames, anime, animals, plants and decorating my home.</p>
            <p class="card-text">You can contact me at <a href="mailto:alejandramartin@outlook.com"> alejandramartin@outlook.com </a> </p>
            <p class="card-text">You can also visit <a href="https://AMartin1987.github.io"> my portfolio</a>. </p>
        </div>    
    </div>
</div>
<a href="https://notbyai.fyi"><img id="profile-picture" src="{% static 'blog/Developed-By-a-Human-Not-By-AI-Badge-black.png' %}" alt="notByAI badge" /> </a>
</div>

{% endblock sidebar %}

mysites/blog/templates/blog/tracking_simple.html
{% extends "blog/layout.html" %}

{% block content %}
{% load tz %}  {# para usar filtros de zona horaria #}
<h1>📊 Estadísticas del blog</h1>

<p><strong>Total de visitas:</strong> {{ total_visitas }}</p>

<table border="1" cellpadding="8">
  <tr>
    <th>IP</th>
    <th>Ciudad</th>
    <th>País</th>
    <th>User Agent</th>
    <th>Fecha</th>
  </tr>
  {% for v in visitas %}
  <tr>
    <td>{{ v.ip }}</td>
    <td>{{ v.city }}</td>
    <td>{{ v.country }}</td>
    <td>{{ v.user_agent|truncatechars:100 }}</td>
    <td>{{ v.start_time|localtime|date:"d/m/Y H:i:s" }}</td>  {# hora en Madrid #}
  </tr>
  {% empty %}
  <tr><td colspan="5">No hay visitas registradas aún.</td></tr>
  {% endfor %}
</table>

{% endblock %}